// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK45tVS1tav_d7C-LxytSVoKjRmvu8hrA',
    appId: '1:74919093555:web:c6d1f24ae28b45b16f0a46',
    messagingSenderId: '74919093555',
    projectId: 'mental-health-app-c42e6',
    authDomain: 'mental-health-app-c42e6.firebaseapp.com',
    storageBucket: 'mental-health-app-c42e6.firebasestorage.app',
    measurementId: 'G-81P3WZXCML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAgVJ6enw1gfGNBOcrbOXeds4fEVML4ak',
    appId: '1:74919093555:android:e519c759f67161146f0a46',
    messagingSenderId: '74919093555',
    projectId: 'mental-health-app-c42e6',
    storageBucket: 'mental-health-app-c42e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGDfJQfR0x4JcAACuICg6DIMC4zf8NHDU',
    appId: '1:74919093555:ios:bde21bc89a2570d26f0a46',
    messagingSenderId: '74919093555',
    projectId: 'mental-health-app-c42e6',
    storageBucket: 'mental-health-app-c42e6.firebasestorage.app',
    iosBundleId: 'com.example.anonymousMentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGDfJQfR0x4JcAACuICg6DIMC4zf8NHDU',
    appId: '1:74919093555:ios:bde21bc89a2570d26f0a46',
    messagingSenderId: '74919093555',
    projectId: 'mental-health-app-c42e6',
    storageBucket: 'mental-health-app-c42e6.firebasestorage.app',
    iosBundleId: 'com.example.anonymousMentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK45tVS1tav_d7C-LxytSVoKjRmvu8hrA',
    appId: '1:74919093555:web:363c504a9bcb61226f0a46',
    messagingSenderId: '74919093555',
    projectId: 'mental-health-app-c42e6',
    authDomain: 'mental-health-app-c42e6.firebaseapp.com',
    storageBucket: 'mental-health-app-c42e6.firebasestorage.app',
    measurementId: 'G-V0W56207CW',
  );
}
